ALTER TABLE `especialidad` ADD `TIPO` VARCHAR(20) NOT NULL ;
ALTER TABLE `especialidad` CHANGE `NOMBRE` `NOMBRE` VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL;
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Alergología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Anestesiología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Cardiología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Dermatología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Endocrinología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Gastroenterología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Geriatría');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Ginecología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Hemoterapia');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Infectología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Nefrología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Neumología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Neurología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Nutriología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Oftalmología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Oncología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Pediatría');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Psiquiatría');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Rehabilitación');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Reumatología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Toxicología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Clínica', 'Urología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Quirúrgica', 'Cardiovascular');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Quirúrgica', 'Aparato digestivo');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Quirúrgica', 'Oral');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Quirúrgica', 'Ortopédica');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Quirúrgica', 'Pediátrica');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Quirúrgica', 'Estética');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Quirúrgica', 'Torácica');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Quirúrgica', 'Neurocirugía');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Médico - Quirúrgica', 'Angiología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Médico - Quirúrgica', 'Venereología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Médico - Quirúrgica', 'Estomatología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Médico - Quirúrgica', 'Ginecología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Médico - Quirúrgica', 'Oftalmología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Médico - Quirúrgica', 'Otorrinolaringología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Médico - Quirúrgica', 'Urología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Médico - Quirúrgica', 'Traumatología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Análisis clínicos');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Anatomía patológica');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Bacteriología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Bioquímica');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Farmacología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Génetica');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Inmunología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Medicina nuclear');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Microbiología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Laboratorio', 'Radiología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Salud', 'Enfermería');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Salud', 'Dietista');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Salud', 'Logopedia');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Salud', 'Fisioterapia');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Salud', 'Podología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Salud', 'Odontología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Salud', 'Optometría');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Salud', 'Psicología');
INSERT INTO `especialidad` (`ID`, `TIPO`, `NOMBRE`) VALUES (NULL, 'Administrativa', 'Administración Hospitalaria');
UPDATE `especialidad` SET `TIPO` = 'Clínica' WHERE TIPO = 'Cl?nica';
UPDATE `especialidad` SET `TIPO` = 'Quirúrgica' WHERE TIPO = 'Quir?rgica';
UPDATE `especialidad` SET `TIPO` = 'Médico - Quirúrgica' WHERE TIPO = 'M?dico - Quir?rgica';
UPDATE `especialidad` SET `NOMBRE` = 'Rehabilitación' WHERE `especialidad`.`ID` = 19;
UPDATE `especialidad` SET `NOMBRE` = REPLACE(NOMBRE, '?', 'í') WHERE TIPO = 'Clínica';